apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pv-claim
  namespace: data-science
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi