apiVersion: v1
kind: Service
metadata:
  name: chatbook
  namespace: data-science
spec:
  type: LoadBalancer
  selector:
    app: chatbook
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8888